package view.gui;

/**
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */


import model.validations.UserDataValidations;
import ficheros.ClassFichero;
import java.io.FileNotFoundException;

/**
 *
 * @author daniellopesp
 */
public class NewJFrameMain extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrameMain
     */
    public NewJFrameMain() {
        initComponents();
        initConfig();
        limpiarForm();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        name = new javax.swing.JLabel();
        jTextFieldName = new javax.swing.JTextField();
        jLabelErrorName = new javax.swing.JLabel();
        dniNif = new javax.swing.JLabel();
        jTextFieldDniNif = new javax.swing.JTextField();
        jLabelErrorDniNif = new javax.swing.JLabel();
        jTextFieldEmail = new javax.swing.JTextField();
        email = new javax.swing.JLabel();
        jLabelErrorEmail = new javax.swing.JLabel();
        birthDate = new javax.swing.JLabel();
        jLabelErrorDate = new javax.swing.JLabel();
        jTextFieldBirthDate = new javax.swing.JTextField();
        age = new javax.swing.JLabel();
        jTextFieldAge = new javax.swing.JTextField();
        zip = new javax.swing.JLabel();
        jTexFieldZip = new javax.swing.JTextField();
        jLabelErrorZip = new javax.swing.JLabel();
        validateButton = new javax.swing.JToggleButton();
        csvButton = new javax.swing.JToggleButton();
        clearButton = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        name.setText("Name");

        jTextFieldName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNameActionPerformed(evt);
            }
        });

        jLabelErrorName.setForeground(new java.awt.Color(255, 0, 0));

        dniNif.setText("DNI/NIF");

        jTextFieldDniNif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDniNifActionPerformed(evt);
            }
        });

        jLabelErrorDniNif.setForeground(new java.awt.Color(255, 0, 0));

        jTextFieldEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldEmailActionPerformed(evt);
            }
        });

        email.setText("Email");

        jLabelErrorEmail.setForeground(new java.awt.Color(255, 0, 0));

        birthDate.setText("Bitrthdate");

        jLabelErrorDate.setForeground(new java.awt.Color(255, 0, 0));

        jTextFieldBirthDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldBirthDateActionPerformed(evt);
            }
        });

        age.setText("Age");

        jTextFieldAge.setEditable(false);
        jTextFieldAge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldAgeActionPerformed(evt);
            }
        });

        zip.setText("Zip");

        jTexFieldZip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTexFieldZipActionPerformed(evt);
            }
        });

        jLabelErrorZip.setForeground(new java.awt.Color(255, 0, 0));

        validateButton.setText("Validate");
        validateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                validateButtonActionPerformed(evt);
            }
        });

        csvButton.setText("CSV");
        csvButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                csvButtonActionPerformed(evt);
            }
        });

        clearButton.setText("Clear");
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(name)
                                    .addComponent(dniNif))
                                .addGap(29, 29, 29)
                                .addComponent(jTextFieldDniNif)
                                .addGap(34, 34, 34)
                                .addComponent(jLabelErrorDniNif, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(72, 72, 72)
                                .addComponent(jTextFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabelErrorName, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(576, 576, 576))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(birthDate)
                            .addComponent(email)
                            .addComponent(age)
                            .addComponent(zip))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldEmail)
                            .addComponent(jTextFieldBirthDate, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextFieldAge, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTexFieldZip, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(csvButton, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(validateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(clearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelErrorZip, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelErrorDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelErrorEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(65, 65, 65))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelErrorName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(name)
                                .addComponent(jTextFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dniNif)
                            .addComponent(jTextFieldDniNif, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabelErrorDniNif, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelErrorEmail, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(email)))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(birthDate)
                        .addComponent(jTextFieldBirthDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabelErrorDate, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(age)
                    .addComponent(jTextFieldAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(zip))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelErrorZip, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTexFieldZip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(validateButton)
                    .addComponent(csvButton)
                    .addComponent(clearButton))
                .addGap(300, 300, 300))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void validateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_validateButtonActionPerformed
        initConfig();
        validateForm();
    }//GEN-LAST:event_validateButtonActionPerformed

    private void jTextFieldNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNameActionPerformed

    }//GEN-LAST:event_jTextFieldNameActionPerformed

    private void jTextFieldBirthDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldBirthDateActionPerformed


    }//GEN-LAST:event_jTextFieldBirthDateActionPerformed

    private void jTextFieldDniNifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDniNifActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDniNifActionPerformed

    private void jTextFieldEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldEmailActionPerformed

    private void jTextFieldAgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldAgeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldAgeActionPerformed

    private void jTexFieldZipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTexFieldZipActionPerformed

    }//GEN-LAST:event_jTexFieldZipActionPerformed

    private void csvButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_csvButtonActionPerformed
        exportToCSV();

    }//GEN-LAST:event_csvButtonActionPerformed

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
        limpiarForm();
    }//GEN-LAST:event_clearButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new NewJFrameMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel age;
    private javax.swing.JLabel birthDate;
    private javax.swing.JToggleButton clearButton;
    private javax.swing.JToggleButton csvButton;
    private javax.swing.JLabel dniNif;
    private javax.swing.JLabel email;
    private javax.swing.JLabel jLabelErrorDate;
    private javax.swing.JLabel jLabelErrorDniNif;
    private javax.swing.JLabel jLabelErrorEmail;
    private javax.swing.JLabel jLabelErrorName;
    private javax.swing.JLabel jLabelErrorZip;
    private javax.swing.JTextField jTexFieldZip;
    private javax.swing.JTextField jTextFieldAge;
    private javax.swing.JTextField jTextFieldBirthDate;
    private javax.swing.JTextField jTextFieldDniNif;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldName;
    private javax.swing.JLabel name;
    private javax.swing.JToggleButton validateButton;
    private javax.swing.JLabel zip;
    // End of variables declaration//GEN-END:variables

    private void initConfig() {
        //Configuracion inicial de los botones
        validateButton.setEnabled(true);
        clearButton.setEnabled(true);
        csvButton.setEnabled(false);

        setLocationRelativeTo(null);

        jTextFieldName.setEditable(true);
        jTexFieldZip.setEditable(true);
        jTextFieldBirthDate.setEditable(true);
        jTextFieldDniNif.setEditable(true);
        jTextFieldEmail.setEditable(true);
        jTextFieldAge.setEditable(true);
    }

    private void limpiarForm() {
        //Dejar Vacios los JTextField
        jTextFieldName.setText("");
        jTexFieldZip.setText("");
        jTextFieldBirthDate.setText("");
        jTextFieldDniNif.setText("");
        jTextFieldEmail.setText("");
    }

    private void exportToCSV() {
        try {
            String line = jTextFieldName.getText() + ","
                    + jTextFieldBirthDate.getText() + ","
                    + jTextFieldDniNif.getText() + ","
                    + jTextFieldEmail.getText() + ","
                    + jTexFieldZip.getText() + "\n";

            ClassFichero.createFile("user_data_DL.csv");
            ClassFichero.writeFile(line);
            ClassFichero.closeFile();

            //Mostrar
            System.out.println("Usuario registrado correctamente");

            // Disable CSV button to prevent multiple registrations
            csvButton.setEnabled(false);
        } catch (FileNotFoundException e) {
            System.out.println("Error saving file");
        }

    }

    private void validateForm() {
        boolean isValid = true;
        String name = jTextFieldName.getText();
        if (!UserDataValidations.checkName(name)) {
            jLabelErrorName.setText("Incorrect Name");
            isValid = false;
        }

        // Validación de la fecha
        String date = jTextFieldBirthDate.getText();
        if (!UserDataValidations.checkFormatDate(date)) {
            jLabelErrorDate.setText("Incorrect Birth date");
            isValid = false;
        }

        // Validación del DNI/NIF
        String id = jTextFieldDniNif.getText();
        if (!UserDataValidations.checkId(1, id)) {
            jLabelErrorDniNif.setText("Incorrect Document");
            isValid = false;

        }
        if (UserDataValidations.checkFormatDate(date)) {
            int edad = UserDataValidations.calculateAge(date);
            jTextFieldAge.setText(String.valueOf(edad));

        }

        // Validación del correo electrónico
        String email = jTextFieldEmail.getText();
        if (!UserDataValidations.checkEmail(email)) {
            jLabelErrorEmail.setText("Incorrect Email");
            isValid = false;
        }

        //Validacion Codigo Postal
        String zip = jTexFieldZip.getText();
        if (!UserDataValidations.checkPostalCode(zip)) {
            jLabelErrorZip.setText("Incorrect Zip");
            isValid = false;
        }
        if (isValid) {
            // Disable editing of all fields
            jTextFieldName.setEditable(false);
            jTextFieldEmail.setEditable(false);
            jTexFieldZip.setEditable(false);
            jTextFieldBirthDate.setEditable(false);
            jTextFieldDniNif.setEditable(false);

            // Enable CSV button
            csvButton.setEnabled(true);

        }

    }

}

 
  
